xis.sql.url=jdbc:postgresql://localhost:5432/seabattle
xis.sql.driver-class-name=org.postgresql.Driver
xis.sql.user=seabattle
xis.sql.password=x_4_fgKl24
server.context-path=/sea-battle
server.address=127.0.0.1
